var state = argument0;
lua_global_set(state, "vk_add", vk_add);
lua_global_set(state, "vk_alt", vk_alt);
lua_global_set(state, "vk_anykey", vk_anykey);
lua_global_set(state, "vk_backspace", vk_backspace);
lua_global_set(state, "vk_control", vk_control);
lua_global_set(state, "vk_decimal", vk_decimal);
lua_global_set(state, "vk_delete", vk_delete);
lua_global_set(state, "vk_divide", vk_divide);
lua_global_set(state, "vk_down", vk_down);
lua_global_set(state, "vk_end", vk_end);
lua_global_set(state, "vk_enter", vk_enter);
lua_global_set(state, "vk_escape", vk_escape);
lua_global_set(state, "vk_f1", vk_f1);
lua_global_set(state, "vk_f10", vk_f10);
lua_global_set(state, "vk_f11", vk_f11);
lua_global_set(state, "vk_f12", vk_f12);
lua_global_set(state, "vk_f2", vk_f2);
lua_global_set(state, "vk_f3", vk_f3);
lua_global_set(state, "vk_f4", vk_f4);
lua_global_set(state, "vk_f5", vk_f5);
lua_global_set(state, "vk_f6", vk_f6);
lua_global_set(state, "vk_f7", vk_f7);
lua_global_set(state, "vk_f8", vk_f8);
lua_global_set(state, "vk_f9", vk_f9);
lua_global_set(state, "vk_home", vk_home);
lua_global_set(state, "vk_insert", vk_insert);
lua_global_set(state, "vk_lalt", vk_lalt);
lua_global_set(state, "vk_lcontrol", vk_lcontrol);
lua_global_set(state, "vk_left", vk_left);
lua_global_set(state, "vk_lshift", vk_lshift);
lua_global_set(state, "vk_multiply", vk_multiply);
lua_global_set(state, "vk_nokey", vk_nokey);
lua_global_set(state, "vk_numpad0", vk_numpad0);
lua_global_set(state, "vk_numpad1", vk_numpad1);
lua_global_set(state, "vk_numpad2", vk_numpad2);
lua_global_set(state, "vk_numpad3", vk_numpad3);
lua_global_set(state, "vk_numpad4", vk_numpad4);
lua_global_set(state, "vk_numpad5", vk_numpad5);
lua_global_set(state, "vk_numpad6", vk_numpad6);
lua_global_set(state, "vk_numpad7", vk_numpad7);
lua_global_set(state, "vk_numpad8", vk_numpad8);
lua_global_set(state, "vk_numpad9", vk_numpad9);
lua_global_set(state, "vk_pagedown", vk_pagedown);
lua_global_set(state, "vk_pageup", vk_pageup);
lua_global_set(state, "vk_pause", vk_pause);
lua_global_set(state, "vk_printscreen", vk_printscreen);
lua_global_set(state, "vk_ralt", vk_ralt);
lua_global_set(state, "vk_rcontrol", vk_rcontrol);
lua_global_set(state, "vk_return", vk_return);
lua_global_set(state, "vk_right", vk_right);
lua_global_set(state, "vk_rshift", vk_rshift);
lua_global_set(state, "vk_shift", vk_shift);
lua_global_set(state, "vk_space", vk_space);
lua_global_set(state, "vk_subtract", vk_subtract);
lua_global_set(state, "vk_tab", vk_tab);
lua_global_set(state, "vk_up", vk_up);

/*
lua_global_set(state, "kLeft", global.kLeft);
lua_global_set(state, "kUp", global.kUp);
lua_global_set(state, "kDown", global.kDown);
lua_global_set(state, "kRight", global.kRight);
lua_global_set(state, "kAttack", global.kAttack);
lua_global_set(state, "kJump", global.kJump);
lua_global_set(state, "kRoll", global.kRoll);
lua_global_set(state, "kChange", global.kChange);
*/


lua_add_function(state, "keyboard_check", ref_keyboard_check);
lua_add_function(state, "keyboard_check_pressed", ref_keyboard_check_pressed);
lua_add_function(state, "keyboard_check_released", ref_keyboard_check_released);

